server:
  port: 8001

spring:
  rabbitmq:
    host: 192.168.0.201
    port: 5672
    username: admin
    password: admin
  application:
    name: helloserver
  cloud:
    bus:
      destination: bus-q
      trace:
        enabled: true
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.0.201
                port: 5672
                username: admin
                password: admin
                publisher-confirms: true
      bindings:
        myInput:
          binder: rabbit1
          destination: things1
        myOutput:
          binder: rabbit1
          destination: things1
        springCloudBusOutput:
          binder: rabbit1
        springCloudBusInput:
          binder: rabbit1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/,http://localhost:10002/eureka/

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

name: '{cipher}995ea1ae0fe0b9d27c98880a981c34d5916b0e0940a28df716548d11a6328c0f'
age: 30
password: 3333331
